<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportTitle }}</title>
    <style>
        :root { color-scheme: light; }
        * { box-sizing: border-box; }
        body {
            margin: 0;
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            color: #0f172a;
            background: #ffffff;
            font-size: 12px;
            line-height: 1.45;
        }
        .page {
            max-width: 1120px;
            margin: 0 auto;
            padding: 24px;
        }
        .header {
            border-bottom: 2px solid #0f766e;
            padding-bottom: 12px;
            margin-bottom: 12px;
        }
        .clinic { margin: 0; font-size: 20px; font-weight: 700; color: #0f766e; }
        .system { margin: 2px 0 10px; font-size: 12px; color: #334155; }
        .meta { margin: 2px 0; color: #334155; }
        .summary {
            display: grid;
            grid-template-columns: repeat(4, minmax(0, 1fr));
            gap: 8px;
            margin: 12px 0 16px;
        }
        .summary-card {
            border: 1px solid #cbd5e1;
            padding: 8px;
            border-radius: 6px;
        }
        .summary-title { margin: 0; font-size: 10px; text-transform: uppercase; color: #475569; }
        .summary-value { margin: 3px 0 0; font-size: 17px; font-weight: 700; color: #0f172a; }
        table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #334155;
            margin-top: 8px;
        }
        th, td {
            border: 1px solid #64748b;
            padding: 7px 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background: #f8fafc;
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: .04em;
        }
        .empty { text-align: center; color: #64748b; padding: 14px; }
        .footer {
            margin-top: 18px;
            border-top: 1px solid #cbd5e1;
            padding-top: 8px;
            color: #475569;
            display: flex;
            justify-content: space-between;
            gap: 12px;
            flex-wrap: wrap;
        }
        .signature {
            margin-top: 22px;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 24px;
        }
        .line {
            border-top: 1px solid #64748b;
            padding-top: 6px;
            color: #475569;
        }
        @media print {
            .page { max-width: none; padding: 0; }
            @page { size: auto; margin: 12mm; }
        }
        @media (max-width: 768px) {
            .summary { grid-template-columns: repeat(2, minmax(0, 1fr)); }
            .signature { grid-template-columns: 1fr; }
        }
    </style>
</head>
<body>
    <main class="page">
        <header class="header">
            <p class="clinic">{{ config('app.name', 'Clinic Name') }}</p>
            <p class="system">Dental Clinic Management System</p>
            <p class="meta"><strong>Report:</strong> {{ $reportTitle }}</p>
            <p class="meta"><strong>Generated By:</strong> {{ $generatedBy }}</p>
            <p class="meta"><strong>Date Generated:</strong> {{ $generatedAt->format('M d, Y h:i A') }}</p>
            <p class="meta"><strong>Date Range:</strong> {{ \Carbon\Carbon::parse($fromDate)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($toDate)->format('M d, Y') }} ({{ $rangeLabel }})</p>
        </header>

        <section class="summary">
            <article class="summary-card">
                <p class="summary-title">Total Patients</p>
                <p class="summary-value">{{ number_format($summary['totalPatients']) }}</p>
            </article>
            <article class="summary-card">
                <p class="summary-title">Total Appointments</p>
                <p class="summary-value">{{ number_format($summary['totalAppointments']) }}</p>
            </article>
            <article class="summary-card">
                <p class="summary-title">Completed Appointments</p>
                <p class="summary-value">{{ number_format($summary['completedCount']) }}</p>
            </article>
            <article class="summary-card">
                <p class="summary-title">Cancelled Appointments</p>
                <p class="summary-value">{{ number_format($summary['cancelledCount']) }}</p>
            </article>
        </section>

        <section>
            <table>
                <thead>
                    <tr>
                        @foreach ($columns as $column)
                            <th>{{ $column }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @forelse ($rows as $row)
                        @if ($reportType === 'patients')
                            <tr>
                                <td>{{ $row->id }}</td>
                                <td>{{ trim(($row->last_name ?? '') . ', ' . ($row->first_name ?? '') . ' ' . ($row->middle_name ?? '')) }}</td>
                                <td>{{ $row->gender ?? 'Unspecified' }}</td>
                                <td>{{ $row->birth_date ? \Carbon\Carbon::parse($row->birth_date)->format('M d, Y') : '-' }}</td>
                                <td>{{ $row->mobile_number ?? '-' }}</td>
                                <td>{{ $row->created_at ? \Carbon\Carbon::parse($row->created_at)->format('M d, Y h:i A') : '-' }}</td>
                            </tr>
                        @elseif ($reportType === 'services')
                            <tr>
                                <td>{{ $row->service_name ?? 'N/A' }}</td>
                                <td>{{ number_format($row->total ?? 0) }}</td>
                            </tr>
                        @elseif ($reportType === 'monthly-summary')
                            <tr>
                                <td>{{ $row->metric ?? '-' }}</td>
                                <td>{{ $row->value ?? '-' }}</td>
                            </tr>
                        @else
                            <tr>
                                <td>{{ $row->id }}</td>
                                <td>{{ trim(($row->last_name ?? '') . ', ' . ($row->first_name ?? '') . ' ' . ($row->middle_name ?? '')) }}</td>
                                <td>{{ $row->service_name ?? 'N/A' }}</td>
                                <td>{{ $row->appointment_date ? \Carbon\Carbon::parse($row->appointment_date)->format('M d, Y h:i A') : '-' }}</td>
                                <td>{{ $row->status ?? '-' }}</td>
                            </tr>
                        @endif
                    @empty
                        <tr>
                            <td colspan="{{ count($columns) }}" class="empty">No records found for the selected criteria.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </section>

        <footer class="footer">
            <div>Generated by Dental Clinic Management System</div>
            <div>Page 1 of 1</div>
        </footer>

        <section class="signature">
            <div class="line">Prepared by</div>
            <div class="line">Approved by</div>
        </section>
    </main>

    <script>
        window.addEventListener('load', () => window.print());
    </script>
</body>
</html>
